<?php $logo = 'Public/logo_LeabYva-removebg-preview.png'; ?>

<div class="pg-hero"><div class="pg-hero-line"></div>
  <div class="chip" data-fr="Nos expertises" data-en="Our expertise">Nos expertises</div>
  <h1><em data-fr="Services" data-en="Services">Services</em><br><span data-fr="&amp; Solutions" data-en="&amp; Solutions">&amp; Solutions</span></h1>
  <p data-fr="Des solutions end-to-end pour chaque étape de votre croissance, de la stratégie à la mise en production." data-en="End-to-end solutions for every stage of your growth, from strategy to production.">Des solutions end-to-end pour chaque étape de votre croissance, de la stratégie à la mise en production.</p>
</div>

<div class="svc-full">
  <div class="sfc-row rv"><span class="sf-num">01</span><span class="sf-name" data-fr="Développement<br>Web &amp; Mobile" data-en="Web &amp; Mobile<br>Development">Développement<br>Web &amp; Mobile</span><p class="sf-desc" data-fr="Applications web et mobiles performantes, évolutives et sécurisées. Nous utilisons les technologies les plus adaptées : React, Next.js, Node.js pour le web, Flutter et React Native pour le mobile. Architecture propre, code documenté, performances optimales." data-en="High-performance, scalable and secure web and mobile applications. We use the technologies best suited to your needs: React, Next.js, Node.js for web, Flutter and React Native for mobile. Clean architecture, documented code, optimal performance.">Applications web et mobiles performantes, évolutives et sécurisées. React, Next.js, Node.js pour le web, Flutter et React Native pour le mobile. Architecture propre, code documenté, performances optimales.</p><div class="sf-tags"><span class="sf-tag">React</span><span class="sf-tag">Next.js</span><span class="sf-tag">Node.js</span><span class="sf-tag">Flutter</span><span class="sf-tag">React Native</span><span class="sf-tag">TypeScript</span></div></div>

  <div class="sfc-row rv" style="transition-delay:.06s"><span class="sf-num">02</span><span class="sf-name">UI / UX<br>Design</span><p class="sf-desc" data-fr="Interfaces intuitives et expériences mémorables. Du research utilisateur aux design systems complets. Chaque décision de design est ancrée dans des données et validée avec vos utilisateurs réels." data-en="Intuitive interfaces and memorable experiences. From user research to complete design systems. Every design decision is data-driven and validated with your real users.">Interfaces intuitives et expériences mémorables. Du research utilisateur aux design systems complets. Chaque décision de design est ancrée dans des données et validée avec vos utilisateurs réels.</p><div class="sf-tags"><span class="sf-tag">Figma</span><span class="sf-tag">Design System</span><span class="sf-tag">UX Research</span><span class="sf-tag">Prototype</span><span class="sf-tag">Accessibility</span></div></div>

  <div class="sfc-row rv" style="transition-delay:.12s"><span class="sf-num">03</span><span class="sf-name" data-fr="Stratégie &amp;<br>Consulting" data-en="Strategy &amp;<br>Consulting">Stratégie &amp;<br>Consulting</span><p class="sf-desc" data-fr="Audit digital complet, feuille de route stratégique et accompagnement opérationnel. Nous analysons votre écosystème digital, identifions les leviers de croissance et construisons avec vous un plan d'action concret et mesurable." data-en="Complete digital audit, strategic roadmap and operational support. We analyze your digital ecosystem, identify growth drivers and build with you a concrete, measurable action plan.">Audit digital complet, feuille de route stratégique et accompagnement opérationnel. Nous analysons votre écosystème, identifions les leviers de croissance et construisons un plan d'action mesurable.</p><div class="sf-tags"><span class="sf-tag">Audit Digital</span><span class="sf-tag">Roadmap</span><span class="sf-tag">KPIs</span><span class="sf-tag">Workshop</span></div></div>

  <div class="sfc-row rv" style="transition-delay:.18s"><span class="sf-num">04</span><span class="sf-name" data-fr="Marketing &amp;<br>Growth" data-en="Marketing &amp;<br>Growth">Marketing &amp;<br>Growth</span><p class="sf-desc" data-fr="Stratégies data-driven pour acquérir, convertir et fidéliser. SEO technique avancé, campagnes SEA et social ads optimisées, marketing automation et e-mail marketing. Chaque action est tracée et optimisée en temps réel." data-en="Data-driven strategies to acquire, convert and retain. Advanced technical SEO, optimized SEA and social ad campaigns, marketing automation and email marketing. Every action is tracked and optimized in real time.">Stratégies data-driven pour acquérir, convertir et fidéliser. SEO technique avancé, campagnes SEA et social ads, marketing automation. Chaque action tracée et optimisée en temps réel.</p><div class="sf-tags"><span class="sf-tag">SEO</span><span class="sf-tag">SEA</span><span class="sf-tag">Social Ads</span><span class="sf-tag">Automation</span><span class="sf-tag">Analytics</span></div></div>

  <div class="sfc-row rv" style="transition-delay:.24s"><span class="sf-num">05</span><span class="sf-name" data-fr="Intelligence<br>Artificielle" data-en="Artificial<br>Intelligence">Intelligence<br>Artificielle</span><p class="sf-desc" data-fr="Intégration de solutions IA sur mesure dans vos processus métier. Chatbots intelligents, systèmes de recommandation, analyse prédictive, automatisation des workflows répétitifs. Nous travaillons avec les derniers LLM et frameworks IA." data-en="Integration of custom AI solutions into your business processes. Intelligent chatbots, recommendation systems, predictive analytics, automation of repetitive workflows. We work with the latest LLMs and AI frameworks.">Intégration de solutions IA dans vos processus métier. Chatbots intelligents, systèmes de recommandation, analyse prédictive, automatisation de workflows. Nous travaillons avec les derniers LLM et frameworks IA.</p><div class="sf-tags"><span class="sf-tag">LLM</span><span class="sf-tag">RAG</span><span class="sf-tag">Automation</span><span class="sf-tag">Python</span><span class="sf-tag">Data Science</span></div></div>

  <div class="sfc-row rv" style="transition-delay:.30s"><span class="sf-num">06</span><span class="sf-name">Cloud &amp;<br>DevOps</span><p class="sf-desc" data-fr="Architecture cloud robuste et scalable. Mise en place de pipelines CI/CD, containerisation Docker/Kubernetes, monitoring avancé et infrastructure as code. Disponibilité 99.9%, sécurité renforcée, scalabilité automatique." data-en="Robust and scalable cloud architecture. CI/CD pipeline setup, Docker/Kubernetes containerization, advanced monitoring and infrastructure as code. 99.9% availability, enhanced security, automatic scalability.">Architecture cloud robuste et scalable. CI/CD, containerisation Docker/Kubernetes, monitoring avancé et infrastructure as code. Disponibilité 99.9%, sécurité renforcée, scalabilité automatique.</p><div class="sf-tags"><span class="sf-tag">AWS</span><span class="sf-tag">GCP</span><span class="sf-tag">Docker</span><span class="sf-tag">Kubernetes</span><span class="sf-tag">Terraform</span></div></div>
</div>

<div class="cta-band" style="border-top:1px solid var(--line)">
  <h2 data-fr="Vous avez un projet en tête ?" data-en="Got a project in mind?">Vous avez un projet en tête ?</h2>
  <div class="cta-right"><p data-fr="Notre équipe est disponible sous 24h pour discuter de votre projet et vous proposer une approche sur mesure." data-en="Our team is available within 24 hours to discuss your project and offer a tailor-made approach.">Notre équipe est disponible sous 24h pour discuter de votre projet et vous proposer une approche sur mesure.</p>
  <a class="btn-a" href="#" onclick="nav_go('cont');return false" data-fr="Nous contacter →" data-en="Contact us →">Nous contacter →</a></div>
</div>

<footer>
  <div class="ft">
    <div class="ft-brand"><div class="fl"><img src="<?= $logo ?>" alt="Leabyva"></div><p data-fr="Votre partenaire pour une transformation digitale réussie." data-en="Your partner for a successful digital transformation.">Votre partenaire pour une transformation digitale réussie.</p><div class="ft-socs"><a class="ft-soc">in</a><a class="ft-soc">𝕏</a><a class="ft-soc">ig</a><a class="ft-soc">fb</a></div></div>
    <div class="ft-col"><h5>Pages</h5><ul><li><a href="#" onclick="nav_go('home');return false" data-fr="Accueil" data-en="Home">Accueil</a></li><li><a href="#" onclick="nav_go('about');return false" data-fr="À propos" data-en="About">À propos</a></li><li><a href="#" onclick="nav_go('port');return false" data-fr="Réalisations" data-en="Portfolio">Réalisations</a></li><li><a href="#" onclick="nav_go('cont');return false">Contact</a></li></ul></div>
    <div class="ft-col"><h5>Contact</h5><ul><li><a href="mailto:hello@leabyva.com">hello@leabyva.com</a></li><li><a>Abidjan, CI</a></li><li><a>Paris, France</a></li></ul></div>
    <div class="ft-col"><h5 data-fr="Légal" data-en="Legal">Légal</h5><ul><li><a href="#" data-fr="Mentions légales" data-en="Legal notice">Mentions légales</a></li><li><a href="#" data-fr="Confidentialité" data-en="Privacy">Confidentialité</a></li></ul></div>
  </div>
  <div class="ft-bottom"><p>© 2025 Leabyva Digital Works.</p><span class="ft-badge">Leabyva <b>♥</b></span></div>
</footer>
